#%RAML 0.8
---
title: Carma API
version: 0.1
#baseUri: http://10.5.248.25:8081/api
baseUri: http://mocksvc.mulesoft.com/mocks/4eaaac10-c180-4e92-bab4-aa01b609c43d/api
mediaType: application/json
/patients:
  post:
    body:
      application/json:
        example: !include examples/sample-dispatch-0912.json   
        schema: !include schema/CarmaRecord_json_V0.2-0912.jsonschema
    responses:
      200:
        body:
          application/json:
      500:
        body:
          application/json:        
  /{id}:
    get:
      responses:
        200:
          body: 
            application/json:         
              schema: !include schema/CarmaRecord_json_V0.2-0912.jsonschema
              example: !include examples/sample-dispatch-0912.json    
    put:
      body:
        application/json:
          example: !include examples/sample-dispatch-0912.json          
          schema: !include schema/CarmaRecord_json_V0.2-0912.jsonschema
    /dispatch:
      post:
        body:
          application/json:
            example: !include examples/Sample.json    
            schema: !include schema/CarmaRecord-json-V1.jsonschema