#%RAML 0.8
---
title: Carma API
version: 0.1
baseUri: http://localhost:8820/carma/api
mediaType: application/json

/patients:
  post:
    body:
      application/json:
        example: !include examples/patient.json    
        schema: !include schema/CarmaRecord_V2.jsonschema
  /{id}:
    get:
      responses:
        200:
          body: 
            application/json:         
              schema: !include schema/CarmaRecord_V2.jsonschema
              example: !include examples/patient.json    
    put:
      body:
        application/json:
          example: !include examples/patient.json          
          schema: !include schema/CarmaRecord_V2.jsonschema
    /dispatch:
      post:
        body:
          application/json:
            example: !include examples/patient.json    
            schema: !include schema/CarmaRecord_V2.jsonschema
            