package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2015-08-31T14:47:24.267-05:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "Carma")
@XmlSeeAlso({ObjectFactory.class, com.corepoint.edims.carma.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Carma {

    @WebResult(name = "SendPatientXMLDataResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @WebMethod(operationName = "SendPatientXMLData", action = "http://tempuri.org/SendPatientXMLData")
    public SendPatientXMLDataResponse sendPatientXMLData(
        @WebParam(partName = "parameters", name = "SendPatientXMLData", targetNamespace = "http://tempuri.org/")
        SendPatientXMLData parameters
    );
}
