package org.tempuri;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2015-08-31T14:47:24.314-05:00
 * Generated source version: 2.5.9
 * 
 */
@WebServiceClient(name = "InboundCarmaXML", 
                  wsdlLocation = "Carma.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class InboundCarmaXML extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "InboundCarmaXML");
    public final static QName Carma = new QName("http://tempuri.org/", "Carma");
    public final static QName Carma12 = new QName("http://tempuri.org/", "Carma12");
    static {
        URL url = InboundCarmaXML.class.getResource("Carma.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(InboundCarmaXML.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "Carma.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public InboundCarmaXML(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InboundCarmaXML(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InboundCarmaXML() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InboundCarmaXML(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InboundCarmaXML(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InboundCarmaXML(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Carma
     */
    @WebEndpoint(name = "Carma")
    public Carma getCarma() {
        return super.getPort(Carma, Carma.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Carma
     */
    @WebEndpoint(name = "Carma")
    public Carma getCarma(WebServiceFeature... features) {
        return super.getPort(Carma, Carma.class, features);
    }
    /**
     *
     * @return
     *     returns Carma
     */
    @WebEndpoint(name = "Carma12")
    public Carma getCarma12() {
        return super.getPort(Carma12, Carma.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Carma
     */
    @WebEndpoint(name = "Carma12")
    public Carma getCarma12(WebServiceFeature... features) {
        return super.getPort(Carma12, Carma.class, features);
    }

}
